// None

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package errors

const (
// QUICLY_WRAPPER as defined in include/quicly_wrapper.h:3

)

const (
	// QUICLY_OK as declared in include/quicly_wrapper.h:11
	QUICLY_OK = iota
	// QUICLY_ERROR_NOTINITILIZED as declared in include/quicly_wrapper.h:12
	QUICLY_ERROR_NOTINITILIZED = 1
	// QUICLY_ERROR_ALREADY_INIT as declared in include/quicly_wrapper.h:13
	QUICLY_ERROR_ALREADY_INIT = 2
	// QUICLY_ERROR_FAILED as declared in include/quicly_wrapper.h:14
	QUICLY_ERROR_FAILED = 3
	// QUICLY_ERROR_CERT_LOAD_FAILED as declared in include/quicly_wrapper.h:15
	QUICLY_ERROR_CERT_LOAD_FAILED = 4
	// QUICLY_ERROR_DECODE_FAILED as declared in include/quicly_wrapper.h:16
	QUICLY_ERROR_DECODE_FAILED = 5
	// QUICLY_ERROR_DESTINATION_NOT_FOUND as declared in include/quicly_wrapper.h:17
	QUICLY_ERROR_DESTINATION_NOT_FOUND = 6
	// QUICLY_ERROR_NOT_OPEN as declared in include/quicly_wrapper.h:18
	QUICLY_ERROR_NOT_OPEN = 7
	// QUICLY_ERROR_STREAM_NOT_FOUND as declared in include/quicly_wrapper.h:19
	QUICLY_ERROR_STREAM_NOT_FOUND = 8
	// QUICLY_ERROR_UNKNOWN_CC_ALGO as declared in include/quicly_wrapper.h:20
	QUICLY_ERROR_UNKNOWN_CC_ALGO = 9
	// QUICLY_ERROR_CANNOT_SEND as declared in include/quicly_wrapper.h:21
	QUICLY_ERROR_CANNOT_SEND = 10
	// QUICLY_ERROR_STREAM_BUSY as declared in include/quicly_wrapper.h:22
	QUICLY_ERROR_STREAM_BUSY = 11
)

const (
	// QUICLY_CC_RENO as declared in include/quicly_wrapper.h:26
	QUICLY_CC_RENO = iota
	// QUICLY_CC_CUBIC as declared in include/quicly_wrapper.h:27
	QUICLY_CC_CUBIC = 1
	// QUICLY_CC_PICO as declared in include/quicly_wrapper.h:28
	QUICLY_CC_PICO = 2
	// QUICLY_CC_LAST as declared in include/quicly_wrapper.h:29
	QUICLY_CC_LAST = 3
)

const (
	// QUICLY_SS_RFC2001 as declared in include/quicly_wrapper.h:33
	QUICLY_SS_RFC2001 = iota
	// QUICLY_SS_DISABLED as declared in include/quicly_wrapper.h:34
	QUICLY_SS_DISABLED = 1
	// QUICLY_SS_SEARCH as declared in include/quicly_wrapper.h:35
	QUICLY_SS_SEARCH = 2
	// QUICLY_SS_LAST as declared in include/quicly_wrapper.h:36
	QUICLY_SS_LAST = 3
)
