// None

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package errors

const (
// QUICLY_WRAPPER as defined in include/quicly_wrapper.h:3

)

const (
	// QUICLY_OK as declared in include/quicly_wrapper.h:11
	QUICLY_OK = iota
	// QUICLY_ERROR_NOTINITILIZED as declared in include/quicly_wrapper.h:12
	QUICLY_ERROR_NOTINITILIZED = 1
	// QUICLY_ERROR_ALREADY_INIT as declared in include/quicly_wrapper.h:13
	QUICLY_ERROR_ALREADY_INIT = 2
	// QUICLY_ERROR_FAILED as declared in include/quicly_wrapper.h:14
	QUICLY_ERROR_FAILED = 3
	// QUICLY_ERROR_DECODE_FAILED as declared in include/quicly_wrapper.h:15
	QUICLY_ERROR_DECODE_FAILED = 4
	// QUICLY_ERROR_DESTINATION_NOT_FOUND as declared in include/quicly_wrapper.h:16
	QUICLY_ERROR_DESTINATION_NOT_FOUND = 5
	// QUICLY_ERROR_NOT_OPEN as declared in include/quicly_wrapper.h:17
	QUICLY_ERROR_NOT_OPEN = 6
	// QUICLY_ERROR_STREAM_NOT_FOUND as declared in include/quicly_wrapper.h:18
	QUICLY_ERROR_STREAM_NOT_FOUND = 7
)
