// None

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bindings

/*
#cgo LDFLAGS: -Llib/ -lquicly -lcrypto -lssl -lm -ldl
#cgo CPPFLAGS: -DDARWIN -D__APPLE__ -D__MACH__ -I../../../ -Iinclude/ -Iinclude/quicly/ -Wno-format
#include "quicly.h"
#include "quicly_wrapper.h"
#include "quicly/streambuf.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Size_t type as declared in _types/_size_t.h:31
type Size_t uint64

// Iovec as declared in _types/_iovec_t.h:31
type Iovec struct {
	Iov_base      unsafe.Pointer
	Iov_len       Size_t
	ref4b778f8    *C.struct_iovec
	allocs4b778f8 interface{}
}
